export enum PointManagement {
  POINTFORSOLUTIONCOMMENT = 15,
  POINTFORENDPROJECT = 20,
  POINTCOLLABORATIONVALIDED = 10,
  POINTMILLELIKE = 30,
}

export enum ParticipantPointManagement {
  POINTFORSOLUTIONCOMMENT = 15,
  POINTFORENDPROJECT = 25,
  POINTCOLLABORATIONVALIDED = 15,
  POINTMILLELIKE = 30,
}
